version: "3.3"
services:
  csvserver:
    image: infracloudio/csvserver
    container_name: assesment 
    ports:
      - "7373:9300"
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputFile:/csvserver/inputdata
    command: "/csvserver/csvserver"


  prom_container:
    image: prom/prometheus:v2.22.0 
    container_name: prom_container
    ports:
      - "7575:9090"
    volumes:
      - ./promconfig.yml:/etc/prometheus/prometheus.yml

